### ISSUE TITLE
Docker-compose does not work as documented - missing image

### ISSUE THREAD

**Issue by jhgoodwin** [citusdata/docker#113]
Documentation states to try:
```bash
$ docker-compose -p citus up
Creating network "citus_default" with the default driver
Pulling master (citusdata/citus:8.0.2)...
ERROR: manifest for citusdata/citus:8.0.2 not found
```
I think the problem is that your hub.docker.com does not contain a tag for 8.0.2

https://hub.docker.com/r/citusdata/citus/tags?page=1

**Comment by hanefi** [comment]
Thanks for pointing that out. Can you use the 8.0.0 version for now, until we fix this issue?

You can use the tag [v8.0.0-2.docker](https://github.com/citusdata/docker/tree/v8.0.0-2.docker) for now

**Comment by hanefi** [comment]
I uploaded the images and now Docker hub contains the latest tags. Let me know if you have any issues
