### ISSUE TITLE
Outdated Alpine images have version mismatches

### ISSUE THREAD

**Issue by hanefi** [citusdata/docker#127]
The Alpine image Dockerfiles are not updated. But we still tag outdated images with the most recent versions in our automated Travis jobs.

All the Alpine docker images that are created after Citus 7.1.0 contain old and outdated Citus binaries ( and possibly outdated pg binaries as well )

https://github.com/citusdata/docker/blob/e63d7ff49c64a6b0a9b9196e0c76321590cdce3c/Dockerfile-alpine#L1-L2

I create a standalone citus server with the following
```
$docker run --name citus_standalone -p 5432:5432 citusdata/citus:8-alpine
```

I see that the PostgreSQL and Citus versions are outdated
```
$docker exec -it citus_standalone psql postgres -U postgres
psql (10.1)
Type "help" for help.

postgres=# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description
---------+---------+------------+------------------------------
 citus   | 7.1-4   | pg_catalog | Citus distributed database
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)
```

**Comment by jasonmp85** [comment]
Yeah, I noticed this a while back!

**Comment by hanefi** [comment]
I will fix this in the next release If I do the packaging.

I also plan on adding one more step to the release checklist issue template for the Alpine Docker images, so that it won't go unnoticed in the future

**Comment by jasonmp85** [comment]
> I can fix this in the next release If I do the packaging.

Sure, or we can do it in-between releases. No worries.

> I also plan on adding one more step to the release checklist issue template for the Alpine Docker images, so that it won't go unnoticed in the future

It is a bit silly we hand-update things. Some scripts would be good.

**Comment by hanefi** [comment]
I manually updated `Dockefile-alpine` on the latest releases. I created a PR to automate this procedure as well
