### ISSUE TITLE
Out of date README

### ISSUE THREAD

**Issue by vladmunteanu** [citusdata/docker#134]
The README seems to be out of date for quite a while, specifying that the underlying Postgres version is 9.6 (1).

I don't think that is the case anymore, as indicated by (2) and (3). 

(1): [README](https://github.com/citusdata/docker#function)
(2): [Dockerfile](https://github.com/citusdata/docker/blob/c07019f1fc468c834de6dbfae6f750382ff7f4bf/Dockerfile#L1)
(3): [Dockerfile-alpine](https://github.com/citusdata/docker/blob/c07019f1fc468c834de6dbfae6f750382ff7f4bf/Dockerfile-alpine#L1)

**Comment by hanefi** [comment]
Thanks for bringing this into our attention Vlad.

We update the docker images, `docker-compose.yml` file when we release new versions of Citus. I overlooked the README file, I will fix this
