### ISSUE TITLE
Error installing packages in the image

### ISSUE THREAD

**Issue by mubaidr** [citusdata/docker#166]
I need to extend the base citus image by installing some package, but running: `apt-get update` fails with error: 
```bash
Err:2 https://repos.citusdata.com/community/debian buster Release
  Could not handshake: The TLS connection was non-properly terminated. [IP: 99.86.181.94 443]

E: The repository 'https://repos.citusdata.com/community/debian buster Release' does not have a Release file.
```

**Comment by mubaidr** [comment]
I have extended official PostgreSQL image using this https://github.com/citusdata/docker/blob/master/Dockerfile and now it works fine.

**Comment by mubaidr** [comment]
Summary: 

- Using official `citusdata/citus` docker image running `apt-get update` causes error: 
```bash
E: The repository 'https://repos.citusdata.com/community/debian buster Release' does not have a Release file.
```

- Using official `postgres` docker image you cannot even install `citus` on it as the citus package is not available for this debian version. 🤦‍♂ 

Whats the solution to this official `citusdata/citus` having invalid registry specified? 
Is there any specific reason the official `postgres` docker images is not supported?

**Comment by mubaidr** [comment]
Solved this by: 

```bash
# clean invalid repositories
rm -rf /etc/apt/sources.list.d/*

apt-get update

# add postgres repositories
/usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
apt-get update
```

**Comment by hanefi** [comment]
>Using official postgres docker image you cannot even install citus on it as the citus package is not available for this debian version. 🤦‍♂

The Citus packages are stored in a seperate repository. If you wish to install Citus packages, you need to install the Citus repository first. You can see the steps at https://www.citusdata.com/download/

>But I still believe the official distribution should be error free.
I agree, I am looking into it

**Comment by hanefi** [comment]
@mubaidr can you share with me some steps to replicate your issue? I could not reproduce your problem. Which tag are you using? I used the latest image and did not run into any problem

```
bash$ docker run -it citusdata/citus bash
```

```
root@38b124415e7e:/# apt-get update
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://apt.postgresql.org/pub/repos/apt buster-pgdg InRelease [58.6 kB]
Get:3 http://deb.debian.org/debian buster InRelease [122 kB]
Get:4 http://apt.postgresql.org/pub/repos/apt buster-pgdg/main amd64 Packages [159 kB]
Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [187 kB]
Get:6 http://apt.postgresql.org/pub/repos/apt buster-pgdg/12 amd64 Packages [861 B]
Get:7 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:8 http://deb.debian.org/debian buster/main amd64 Packages [7,907 kB]
Get:10 http://deb.debian.org/debian buster-updates/main amd64 Packages [7,380 B]
Get:9 https://repos.citusdata.com/community/debian buster InRelease [23.2 kB]
Get:11 https://repos.citusdata.com/community/debian buster/main amd64 Packages [14.3 kB]
Fetched 8,594 kB in 5s (1,759 kB/s)
Reading package lists... Done
```

**Comment by mubaidr** [comment]
Sure, I will check and report again.

**Comment by mubaidr** [comment]
Tested `latest` and `9.2` tags, both works fine. Don't know why this happened earlier. :( Closing this issue. Thanks
