### ISSUE TITLE
Understanding pg_worker_list.conf

### ISSUE THREAD

**Issue by hackermd** [citusdata/docker#18]
I am trying to understand your `docker-compose` setup, where worker nodes get dynamically registered via a shared volume. In particular, I would like to understand the `pg_worker_list.conf` file, which doesn't seem to be documented (anymore). I am setting up citus clusters via ansible and it would be convenient to be able to register worker nodes upon deployment without having to connect to the master database server and call `master_add_node()`.

Could you please elaborate on the use of a `pg_worker_list.conf` file and potential pitfalls?

**Comment by jasonmp85** [comment]
Hey @hackermd… I know this is a _super_ delayed, but `pg_worker_list.conf` is a deprecated way of specifying worker nodes; everything is indeed done with `master_add_node` now, and we are in the process of removing our own `pg_worker_list.conf` usage now (see #29)

**Comment by hackermd** [comment]
@jasonmp85 thanks for the notice! This is good to know @riccardomurri
