### ISSUE TITLE
Feature request: Alpine Version 9.6.2-alpine

### ISSUE THREAD

**Issue by austinnichols101** [citusdata/docker#19]
I would like to see a version of the container based on the official postgres 9.6.2-alpine image.  The overall image and attack surface is MUCH smaller on the Alpine image.

**Comment by jasonmp85** [comment]
I played around with this a while back and was able to get it working. Our repo host doesn't offer APK hosting, but with a little effort I was able to produce an alpine image that compiles Citus from source. I'll share my findings in the coming week or so when I get around to it.

**Comment by jasonmp85** [comment]
@austinnichols101 There are now `alpine`, `7-alpine`, `7.0-alpine`, and `7.0.1-alpine` tags. I haven't tested them terribly much but they should work. If you're interested, let me know how they look.
