### ISSUE TITLE
`docker-compose down` drops volumes and deletes all data

### ISSUE THREAD

**Issue by lithp** [citusdata/docker#22]
This came up in Drift, [the documentation](https://docs.docker.com/compose/reference/down/) for `down` makes it sound like data should still be around after `down`.

I think this is because the base postgres image [uses a volume in `/var/lib/postgresql/data`](https://github.com/docker-library/postgres/blob/3d4e5e9f64124b72aa80f80e2635aff0545988c6/9.6/Dockerfile#L62) where the compose spec exposes [the volume at `/var/run/postgresql`](https://github.com/citusdata/docker/blob/master/docker-compose.yml#L9)?

I realize this is an anemic ticket, it's mostly a token so I don't forget to ask you about this.

**Comment by jasonmp85** [comment]
Closing this… the `var/run` volume is for exposing the socket file between Citus instances. `docker-compose down` is doing what it says it does (drops all containers, networks, and volumes). The PostgreSQL data directory is the same one we use, and it is not external.
