### ISSUE TITLE
How to use the hyperscale docker images?

### ISSUE THREAD

**Issue by mintuhouse** [citusdata/docker#295]
[Ref](https://github.com/citusdata/docker/pull/280#pullrequestreview-843435274)

Are the new hyperscale citus images published somewhere?

**Comment by gurkanindibay** [comment]
Hi @mintuhouse 
Thanks for your interest. We don't publish this image into dockerhub . But you can build and run locally using the PR description you referenced. If you have problems, you can write here the problems you experienced and I can help you
Thanks
