### ISSUE TITLE
Docker image for tutorial convenience

### ISSUE THREAD

**Issue by begriffs** [citusdata/docker#3]
@ozgune, @lithp and I were thinking about the Docker possibilities to make the Citus tutorials easy for new users.

We thought of three broad possibilities:
1. Include the python tutorial scripts and python runtime in the main Citus docker container
2. Create a new tutorial container which builds on top of the Citus container (exploring that here https://github.com/citusdata/tutorial-resources/pull/7)
3. Do not use docker in the tutorials at all, distribute separate resources for each OS

The advantage of option 1 is fewer instructions. if you have Citus you can run the tutorial. Disadvantage is bloat.

Advantage of option 2 is it follows the docker philosophy of building containers on one another. Building the citus or the tutorial container will speed the build of the other, and they stay separate. The disadvantage is explaining this nuance to potential users.

The advantage of option three is that it simplifies the tutorial instructions. Also @lithp has already packaged it for multiple OSes and made it work. The disadvantage is that the tutorials would not work with all standard installation methods of Citus.

Opinions?

/cc @jasonmp85 @sumedhpathak @samay-sharma

**Comment by jasonmp85** [comment]
I think the tarballs are gone now, and we have other tutorial approaches we've explored. @begriffs… I'm closing this; re-open if you still have concerns, plz.
