### ISSUE TITLE
Build a "latest" image based on nightlies

### ISSUE THREAD

**Issue by travisjeffery** [citusdata/docker#5]
Hey there,

Do you mind putting out an update? Would love to have this: https://github.com/citusdata/citus/pull/445

Thanks

**Comment by jasonmp85** [comment]
Hey @travisjeffery: At the moment we're only providing Docker images of official Citus releases.

That pull request is slated for the upcoming Citus 5.1 and as such is not yet in our Docker image (or any existing Citus release).

We may explore providing a `latest` tag that points to a nightly build, but this isn't something we've set up at the moment.

Leaving this open to track a possible solution to your request (I rewrote the title), but for a faster workaround, feel free to drop into Slack or IRC, or just send us an email.

**Comment by jasonmp85** [comment]
I've decided upon building a `nightly` tag for providing nightly builds from Citus `master` and reserving `latest` for its typical (I think?) use as "latest release" (e.g. 5.1.0).
