### ISSUE TITLE
citusdata/citus:7.2.0 doesn't seem to exist

### ISSUE THREAD

**Issue by bitglue** [citusdata/docker#67]
```console
$ docker-compose -p citus up
Pulling master (citusdata/citus:7.2.0)...
ERROR: manifest for citusdata/citus:7.2.0 not found
```

[Looking at Docker Hub](https://hub.docker.com/r/citusdata/citus/tags/), seems there isn't a 7.2.0 tag.

**Comment by sumedhpathak** [comment]
Thanks for reporting this, and we're looking into it. @begriffs will provide an update soon.

**Comment by begriffs** [comment]
Hi @bitglue, we previously hadn't tagged 7.2 on Docker Hub but it's now available. I just pulled it and verified it runs locally. See whether it works for you now, and we can close the issue.

**Comment by bitglue** [comment]
Works great, thanks!
